name: flutter_clean_calendar
description: Simple and clean flutter calendar with ability to slide up/down to show weekly/monthly calendar.
version: 1.0.2
author: "Carlos Pe√±a <pmcarlosdev@gmail.com>"
homepage: "https://github.com/pmcarlos/flutter_clean_calendar"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_utils:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
